### PR TITLE
Templatize GHA workflows

### PR DESCRIPTION
**Pull request by LindseySaari**
This PR templatizes the GHA deploy.yml and push-image.yml workflows to make them reuseable for applications on the platform-console. 

I image that when we spin up new apps on the console, we will want to commit these two workflows to the repo. To customize for each app, we will just need to define the env vars near the top of the workflow files.

I started to go down the [GHA starter workflow path](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization), but it didn't make sense since we will want to do the heavy lifting for the new apps and auto commit the templatized workflow files (instead of having devs select a starter template and manually doing it)

I explored the suggestions form @ericboehs but reuseable workflows within a Github Organization only apply to internal or private repos, not public (as in the platform-console-api :cry)

### CODE REVIEW

**Comment by ericboehs** [comment]
Would we be able to use this? https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/

**Comment by LindseySaari** [comment]
> Would we be able to use this? https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
> 
> Ooo! Or this? https://github.blog/changelog/2022-01-21-share-github-actions-within-your-enterprise/

Nice! I don't think that the first option would work because the workflows would need to be in the same repository, but the latter might work actually!

**Comment by LindseySaari** [comment]
> > Would we be able to use this? https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
> > Ooo! Or this? https://github.blog/changelog/2022-01-21-share-github-actions-within-your-enterprise/
> 
> Nice! I don't think that the first option would work because the workflows would need to be in the same repository, but the latter might work actually!

@ericboehs Nvm 😞  Looks like the reuseable actions can't be used in workflows in public repos. "These Actions in internal repositories can only be used by workflows defined in other private and internal repositories but cannot be used in workflows defined within any public repositories."

**Comment by LindseySaari** [comment]
> > > Would we be able to use this? https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally/
> > > Ooo! Or this? https://github.blog/changelog/2022-01-21-share-github-actions-within-your-enterprise/
> > 
> > 
> > Nice! I don't think that the first option would work because the workflows would need to be in the same repository, but the latter might work actually!
> 
> ~@ericboehs Nvm 😞 Looks like the reuseable actions can't be used in workflows in public repos. "These Actions in internal repositories can only be used by workflows defined in other private and internal repositories but cannot be used in workflows defined within any public repositories."~
> 
> @ericboehs Maybe I read that wrong. I _think_ you can reuse workflows amongst public repos, but can't share from private => public. Going to poke some more

Well... it looks like you can only share amongest internal or private repos... not public 😭 [ See docs here](https://docs.github.com/en/enterprise-cloud@latest/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-access-to-components-in-an-internal-repository). platform-console-api doesn't have the configurable Access settings under [Actions/General](https://github.com/department-of-veterans-affairs/platform-console-api/settings/actions)

**Pull request closed without merging**
